# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: t.pernetcoudrier@gmail.com
author_name: Thomas Pernet
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyter_cell_selection
project_short_description: A JupyterLab extension.
python_name: jupyter_cell_selection
repository: ''
test: false

